version: '3.8'

services:
  # 后端 API
  backend:
    build:
      context: ../backend
      dockerfile: ../deploy/Dockerfile.backend
    container_name: noiquest_backend
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3001
    networks:
      - noiquest_network
    expose:
      - "3001"

  # 前端
  frontend:
    build:
      context: ../frontend
      dockerfile: ../deploy/Dockerfile.frontend
    container_name: noiquest_frontend
    restart: always
    networks:
      - noiquest_network
    expose:
      - "80"

networks:
  noiquest_network:
    driver: bridge
